FROM python:3.10-slim

WORKDIR /app
# Copy your requirements file
COPY requirements.txt .           


RUN pip install --no-cache-dir -r requirements.txt

COPY src/validate.py .
COPY src/logger_utils.py .

CMD ["python", "validate.py"]
